### ISSUE TITLE
Translated videos are not found

### ISSUE THREAD

**Issue by runepiper** [astehlik/typo3-extension-html5mediakit#19]
When a non-admin editor creates a translation for a video, the video is not found (_No media element was found in the current content element._). If an admin creates a translation for a video, the video is shown as expected.

I guess this is more a permission issue of our installation, because the underlying code show fairly standard repository queries. I wonder what could be the issue.

**Comment by astehlik** [comment]
Hi @runepiper,

as you already suspected the issue occurred due to missing write permissions to the language field of the media records.

Cheers, Alex
