### ISSUE TITLE
Uncaught TYPO3 Exception

### ISSUE THREAD

**Issue by kroja** [astehlik/typo3-extension-html5mediakit#2]
Hi,

I came across an error which probably is caused by this extension (if I understand things right).

TYPO3-pages with an content element "audio/video" _sometimes_ produce the following error:  

```
#1297759968: Exception while property mapping at property path "":The source is not of type string, array, float, integer or boolean, but of type "object" (More information)

TYPO3\CMS\Extbase\Property\Exception thrown in file
/srv/www/htdocs/rz228/html/cms/typo3/sysext/extbase/Classes/Property/PropertyMapper.php in line 112.

31 TYPO3\CMS\Extbase\Property\PropertyMapper::convert(Sto\Html5mediakit\Domain\Model\Media, "Sto\Html5mediakit\Domain\Model\Audio", TYPO3\CMS\Extbase\Mvc\Controller\MvcPropertyMappingConfiguration)

/srv/www/htdocs/rz228/html/cms/typo3/sysext/extbase/Classes/Mvc/Controller/Argument.php:
00376:    }
00377:    try {
00378:     $this->value = $this->propertyMapper->convert($rawValue, $this->dataType, $this->propertyMappingConfiguration);
00379:    } catch (TargetNotFoundException $e) {
00380:     // for optional arguments no exeption is thrown.
```

(30 further such entries)

But strange: it comes without any obvious reason (at least for me). And it goes the same way. It is not reproducable but occurs several times a day. Sometimes it works as expacted, sometimes it produces this error.
- TYPO3 6.2.15
- PHP 5.3.17
- html5mediakit 1.0.0

Any hints to solve this problem?

See full error log here:
[TYPO3 Exception_html5mediakit_151110.pdf](https://github.com/astehlik/typo3-extension-html5mediakit/files/31973/TYPO3.Exception_html5mediakit_151110.pdf)

Thanx for your help,
Jan

**Comment by christophlehmann** [comment]
Same here

**Comment by astehlik** [comment]
Thank you for reporting the issue and sorry for the late reply. I'm not sure if the issue is still relevant.

I created a feature branch `1.x` that contains 2 changes that might help with the reported problem. I can only speculate that this is some TypoScript caching issue with the Extbase mapping config.

Please let me know if this helps and I'll draft a 1.x bugfix release.
