### ISSUE TITLE
SQL error: 'Incorrect integer value: '' for column 'sys_language_uid'

### ISSUE THREAD

**Issue by RobertKesseler** [astehlik/typo3-extension-html5mediakit#3]
Hi there,

I get 
> 2: SQL error: 'Incorrect integer value: '' for column 'sys_language_uid' at row 1' (tx_html5mediakit_domain_model_media:NEW5cff6edb3fc1d073673320)

when trying to add video, after saving

TYPO3 9.5.6
PHP 7.3.4
html5mediakit 9.0.0

Possible solution: 
https://stackoverflow.com/questions/40542151/typo3-sql-error-incorrect-integer-value-for-column-sys-language-uid-at

I will try to check if suggested solution helps if I find the time

Kind Regards
Robert

**Comment by RobertKesseler** [comment]
in /typo3conf/ext/html5mediakit/Configuration/TCA/tx_html5mediakit_domain_model_media.php
around line 162 add:  'default' => 0,

works for me

```
'sys_language_uid' => [
            'exclude' => 1,
            'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.language',
            'config' => [
                'type' => 'select',
                'foreign_table' => 'sys_language',
                'foreign_table_where' => 'ORDER BY sys_language.title',
                'items' => [
                    [
                        'LLL:EXT:lang/locallang_general.xlf:LGL.allLanguages',
                        -1,
                    ],
                    [
                        'LLL:EXT:lang/locallang_general.xlf:LGL.default_value',
                        0,
                    ],
                'default' => 0,
                ],
            ],
        ],
```

**Comment by astehlik** [comment]
Thank you for reporting this issue.

A new fixed version was released.
