### ISSUE TITLE
Add own Resources paths for templates/layouts/partials

### ISSUE THREAD

**Issue by vmans** [astehlik/typo3-extension-html5mediakit#4]
Rather basic: set own Resources paths for templates/layouts/partials in constants/setup.

And/or add Bootstrap embed tags options, for instance "embed-responsive embed-responsive-4by3".

**Comment by astehlik** [comment]
Thank you for taking the time for creating an issue. Please excuse my late reply, had a lot on my plate these days :(

Constants for adding additional template paths were introduced in the current develop branch and will be included in the next release. Feel free to check it out.

Can you elaborate your use case for the `embed-responsive classes`? Browsers should scale videos with the correct aspect ratio (just like images) automatically when `width` is set to `100%` and `height` to `auto`.

Cheers
Alex

**Comment by astehlik** [comment]
@vmans I'm closing this for now. Feel free to drop me a comment when it should be reopened.
