### ISSUE TITLE
After update to the developer i get the following error

### ISSUE THREAD

**Issue by helmut-winkelbach** [astehlik/typo3-extension-html5mediakit#6]
Oops, an error occurred!
An exception occurred while executing 'SELECT `uid`, `l10n_parent`, `mp3`, `ogg`, `h264`, `ogv`, `poster`, `web_m`, `deleted` FROM `tx_html5mediakit_domain_model_media` WHERE `uid` = ?' with params [15]: Unknown column 'poster' in 'field list'

I got even more errors, BE and FE is not avoilable.
Oops, an error occurred!
The requested resource "/module/tools/ExtensionmanagerExtensionmanager" was not found.
More information regarding this error might be available online.With the TER version translations didn't show content elements.

**Comment by astehlik** [comment]
The reason you are getting this error is that a new column `poster` was introduced with #5 

Please run the database analyser and add the missing column as described [here](https://docs.typo3.org/m/typo3/guide-installation/master/en-us/Upgrade/RunTheDatabaseAnalyzer/Index.html).

Cheers
Alex
